# Generated by Django 5.2.4 on 2025-07-16 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('ean', models.CharField(max_length=13)),
                ('sku', models.CharField(max_length=50)),
                ('loja', models.CharField(default='-', max_length=75)),
                ('preco_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('marketplace', models.CharField(default='Desconhecido', max_length=50)),
                ('change_price', models.IntegerField(default=0)),
                ('key_loja', models.CharField(default='sem_loja', max_length=100)),
                ('key_sku', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.TextField()),
                ('review', models.FloatField(default=0.0)),
                ('imagem', models.URLField(default='https://via.placeholder.com/150', max_length=500)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('preco_pricing', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductURL',
            fields=[
                ('ean_key', models.CharField(primary_key=True, serialize=False)),
                ('ean', models.CharField(max_length=13)),
                ('brand', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('client_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
