# Generated by Django 5.2.4 on 2025-10-19 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='categoria',
            field=models.CharField(choices=[('cosmetico', 'Cosmetico'), ('eletronico', 'Eletronico')], default='sem categoria', max_length=13),
        ),
        migrations.AlterField(
            model_name='producturl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=13)),
                ('loja', models.CharField(max_length=100)),
                ('key_loja', models.CharField(max_length=200)),
                ('preco_final_antigo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_final_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(max_length=500)),
                ('descricao', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['ean', 'loja'], name='priceapi_pr_ean_6f797c_idx'), models.Index(fields=['timestamp'], name='priceapi_pr_timesta_a65938_idx')],
            },
        ),
    ]
