# Generated by Django 5.2 on 2025-10-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='preco_buybox',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
